### ISSUE TITLE
Contribution Instructions out of date?

### ISSUE THREAD

**Issue by den1k** [juji-io/datalevin#245]
just tried fixing #244 but can't properly start the project. tried deps.edn and getting this error:

```clojure
(ns datalevin.test.conn
  (:require
   [datalevin.test.core :as tdc :refer [db-fixture]]
   [clojure.test :refer [deftest testing is use-fixtures]]
   [datalevin.core :as d]
   [datalevin.db :as db]
   [datalevin.constants :as c]
   [datalevin.util :as u])
  (:import [java.util Date UUID]))
Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:445).
org.bouncycastle.crypto.generators.Argon2BytesGenerator
```

Then tried leiningen and getting this error:

```clojure
Error loading nrepl.server: Could not locate nrepl/server__init.class, nrepl/server.clj or nrepl/server.cljc on classpath.
Error loading incomplete.core: Could not locate incomplete/core__init.class, incomplete/core.clj or incomplete/core.cljc on classpath.
Syntax error (ClassNotFoundException) compiling at (/private/var/folders/wx/xr_w7fln6dl9k13wh3mj3m5w0000gn/T/form-init14312025131968719262.clj:1:1612).
nrepl.server

Full report at:
/var/folders/wx/xr_w7fln6dl9k13wh3mj3m5w0000gn/T/clojure-7745510090509568626.edn
```

was referencing doc/install.md

**Comment by den1k** [comment]
@huahaiy I think what would be most helpful are the command line options to get a remote repl going. that way people can connect to something that works independent of their editor.

**Comment by den1k** [comment]
when including datalevin as a `local/root` dependency from deps.edn, I get this error on load:

```clojure
Execution error (ClassNotFoundException) at jdk.internal.loader.BuiltinClassLoader/loadClass (BuiltinClassLoader.java:641).
clojure.core$seq_QMARK___5471
Syntax error macroexpanding at (clojure/tools/analyzer/jvm.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7648)
java.lang.NoClassDefFoundError: clojure/core$seq_QMARK___5471
	at clojure.tools.reader.impl.utils$fn__929.invokeStatic(utils.clj:17)
java.lang.ClassNotFoundException: clojure.core$seq_QMARK___5471
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at clojure.tools.reader.impl.utils$fn__929.invokeStatic(utils.clj:17)
	at clojure.tools.reader.impl.utils$fn__929.invoke(utils.clj:17)
	at clojure.tools.reader.impl.utils__init.load(Unknown Source)
	at clojure.tools.reader.impl.utils__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForName(RT.java:2218)
	at clojure.lang.RT.loadClassForName(RT.java:2237)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6922.invoke(core.clj:6175)
	at clojure.core$load.invokeStatic(core.clj:6174)
	at clojure.core$load.doInvoke(core.clj:6158)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.core$load_one.invokeStatic(core.clj:5947)
	at clojure.core$load_one.invoke(core.clj:5942)
	at clojure.core$load_lib$fn__6864.invoke(core.clj:5989)
	at clojure.core$load_lib.invokeStatic(core.clj:5988)
	at clojure.core$load_lib.doInvoke(core.clj:5967)
	at clojure.lang.RestFn.applyTo(RestFn.java:145)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6030)
	at clojure.core$load_libs.doInvoke(core.clj:6014)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6052)
	at clojure.tools.reader.reader_types$loading__6789__auto____921.invoke(reader_types.clj:9)
	at clojure.tools.reader.reader_types__init.load(Unknown Source)
	at clojure.tools.reader.reader_types__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForName(RT.java:2218)
	at clojure.lang.RT.loadClassForName(RT.java:2237)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6922.invoke(core.clj:6175)
	at clojure.core$load.invokeStatic(core.clj:6174)
	at clojure.core$load.doInvoke(core.clj:6158)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.core$load_one.invokeStatic(core.clj:5947)
	at clojure.core$load_one.invoke(core.clj:5942)
	at clojure.core$load_lib$fn__6864.invoke(core.clj:5989)
	at clojure.core$load_lib.invokeStatic(core.clj:5988)
	at clojure.core$load_lib.doInvoke(core.clj:5967)
	at clojure.lang.RestFn.applyTo(RestFn.java:145)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6030)
	at clojure.core$load_libs.doInvoke(core.clj:6014)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6052)
	at clojure.tools.reader$loading__6789__auto____4373.invoke(reader.clj:9)
	at clojure.tools.reader__init.load(Unknown Source)
	at clojure.tools.reader__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForName(RT.java:2218)
	at clojure.lang.RT.loadClassForName(RT.java:2237)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6922.invoke(core.clj:6175)
	at clojure.core$load.invokeStatic(core.clj:6174)
	at clojure.core$load.doInvoke(core.clj:6158)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.core$load_one.invokeStatic(core.clj:5947)
	at clojure.core$load_one.invoke(core.clj:5942)
	at clojure.core$load_lib$fn__6864.invoke(core.clj:5989)
	at clojure.core$load_lib.invokeStatic(core.clj:5988)
	at clojure.core$load_lib.doInvoke(core.clj:5967)
	at clojure.lang.RestFn.applyTo(RestFn.java:145)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6030)
	at clojure.core$load_libs.doInvoke(core.clj:6014)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6052)
	at clojure.core$require.doInvoke(core.clj:6052)
	at clojure.lang.RestFn.invoke(RestFn.java:706)
	at clojure.tools.analyzer.jvm$eval2265$loading__6803__auto____2266.invoke(jvm.clj:9)
	at clojure.tools.analyzer.jvm$eval2265.invokeStatic(jvm.clj:9)
	at clojure.tools.analyzer.jvm$eval2265.invoke(jvm.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6922.invoke(core.clj:6175)
	at clojure.core$load.invokeStatic(core.clj:6174)
	at clojure.core$load.doInvoke(core.clj:6158)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.core$load_one.invokeStatic(core.clj:5947)
	at clojure.core$load_one.invoke(core.clj:5942)
	at clojure.core$load_lib$fn__6864.invoke(core.clj:5989)
	at clojure.core$load_lib.invokeStatic(core.clj:5988)
	at clojure.core$load_lib.doInvoke(core.clj:5967)
	at clojure.lang.RestFn.applyTo(RestFn.java:145)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6030)
	at clojure.core$load_libs.doInvoke(core.clj:6014)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6052)
	at clojure.core$require.doInvoke(core.clj:6052)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at cloroutine.impl$eval2257$loading__6803__auto____2258.invoke(impl.cljc:1)
	at cloroutine.impl$eval2257.invokeStatic(impl.cljc:1)
	at cloroutine.impl$eval2257.invoke(impl.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6922.invoke(core.clj:6175)
	at clojure.core$load.invokeStatic(core.clj:6174)
	at clojure.core$load.doInvoke(core.clj:6158)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.core$load_one.invokeStatic(core.clj:5947)
	at clojure.core$load_one.invoke(core.clj:5942)
	at clojure.core$load_lib$fn__6864.invoke(core.clj:5989)
	at clojure.core$load_lib.invokeStatic(core.clj:5988)
	at clojure.core$load_lib.doInvoke(core.clj:5967)
	at clojure.lang.RestFn.applyTo(RestFn.java:145)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6030)
	at clojure.core$load_libs.doInvoke(core.clj:6014)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6052)
	at clojure.core$require.doInvoke(core.clj:6052)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at cloroutine.core$eval2249$loading__6803__auto____2250.invoke(core.cljc:1)
	at cloroutine.core$eval2249.invokeStatic(core.cljc:1)
	at cloroutine.core$eval2249.invoke(core.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6922.invoke(core.clj:6175)
	at clojure.core$load.invokeStatic(core.clj:6174)
	at clojure.core$load.doInvoke(core.clj:6158)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.core$load_one.invokeStatic(core.clj:5947)
	at clojure.core$load_one.invoke(core.clj:5942)
	at clojure.core$load_lib$fn__6864.invoke(core.clj:5989)
	at clojure.core$load_lib.invokeStatic(core.clj:5988)
	at clojure.core$load_lib.doInvoke(core.clj:5967)
	at clojure.lang.RestFn.applyTo(RestFn.java:145)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6030)
	at clojure.core$load_libs.doInvoke(core.clj:6014)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6052)
	at clojure.core$require.doInvoke(core.clj:6052)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at missionary.core$eval2243$loading__6803__auto____2244.invoke(core.cljc:1)
	at missionary.core$eval2243.invokeStatic(core.cljc:1)
	at missionary.core$eval2243.invoke(core.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6922.invoke(core.clj:6175)
	at clojure.core$load.invokeStatic(core.clj:6174)
	at clojure.core$load.doInvoke(core.clj:6158)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at clojure.core$load_one.invokeStatic(core.clj:5947)
	at clojure.core$load_one.invoke(core.clj:5942)
	at clojure.core$load_lib$fn__6864.invoke(core.clj:5989)
	at clojure.core$load_lib.invokeStatic(core.clj:5988)
	at clojure.core$load_lib.doInvoke(core.clj:5967)
	at clojure.lang.RestFn.applyTo(RestFn.java:145)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6030)
	at clojure.core$load_libs.doInvoke(core.clj:6014)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6052)
	at clojure.core$require.doInvoke(core.clj:6052)
	at clojure.lang.RestFn.invoke(RestFn.java:808)
	at tesserae.db$eval1913$loading__6803__auto____1914.invoke(db.clj:1)
	at tesserae.db$eval1913.invokeStatic(db.clj:1)
	at tesserae.db$eval1913.invoke(db.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.eval(Compiler.java:7132)
	at clojure.core$eval.invokeStatic(core.clj:3229)
	at clojure.core$eval.invoke(core.clj:3225)
	at nrepl.middleware.interruptible_eval$evaluate$fn__968$fn__969.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:428)
	at nrepl.middleware.interruptible_eval$evaluate$fn__968.invoke(interruptible_eval.clj:87)
	at clojure.main$repl$read_eval_print__9228$fn__9231.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9228.invoke(main.clj:437)
	at clojure.main$repl$fn__9237.invoke(main.clj:459)
	at clojure.main$repl.invokeStatic(main.clj:459)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1526)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__999$fn__1003.invoke(interruptible_eval.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__1067$fn__1071.invoke(session.clj:202)
	at nrepl.middleware.session$session_exec$main_loop__1067.invoke(session.clj:201)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by huahaiy** [comment]
I am not a heavy clj command line users, so some help will be needed for the setup.

As to leiningen, I don't think we explicitly need nrepl.server, so I am not sure what the error is about. Maybe it is specific to your setup?

**Comment by huahaiy** [comment]
I have cleaned up the `deps.edn` file, it seems to work. Re-open if there's additional issue.
